#!/bin/bash

# Este script move cada uma das ORIGENS para o data-dir,
# substituindo-os por links dentro do repo-dir.
#
# ATENCAO !!
# ARQUIVOS SALVOS NOS DIRETORIOS ABAIXO, DENTRO DO REPOSITORIO GIT, SERAO
# PERDIDOS A CADA PUSH.

ORIGENS=(
  # Caminhos relativos ao $OPENSHIFT_REPO_DIR:
  emoncmsdata/phpfina   # torna-se um link $OPENSHIFT_REPO_DIR/emoncmsdata/phpfina -> $OPENSHIFT_DATA_DIR/emoncmsdata/phpfina
)

echo "-- Ajustando diretorios persistentes..."

for DIR in ${ORIGENS[*]}; do
  ORIGEM="${OPENSHIFT_REPO_DIR}$DIR"
  DESTINO="${OPENSHIFT_DATA_DIR}$DIR"

  mkdir "$ORIGEM"
  if [ -d "$ORIGEM" ]; then
    if [ -d "$DESTINO" ]; then
      echo "  - Relinkando diretorio: $ORIGEM -> $DESTINO"
      rm -rf "$ORIGEM"
    else
      echo "  - Criando diretorio: $ORIGEM -> $DESTINO"
      mkdir -p ${DESTINO%/*}
      mv $ORIGEM $DESTINO
    fi
    ln -sf "$DESTINO" "$ORIGEM"
  else
    echo "  - Ignorando diretorio inexistente: $ORIGEM"
  fi
done